id: 9a38db6c9b044acaa8d114593ec8cfa4
title: Toh_308-Questions%20Regarding%20Death%20and%20Transmigration-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-008
